### PR TITLE
Update purei9_unofficial and add country code config

### LINKED ISSUE #73: Giving up due to no left retries. Wrong credentials?
Since the beginning of August my Pure i9 has not been unavailable in HA.

In the logs I get:
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate

Nothing has changed in my system to cause an authentication issue.
In case it was on the account side I deleted my account and created a new one with matching username and password. No change.

I tried removing and reinstalling the integration but it won't authenticate during the install.

I have restored to a backup in a state where the integration was working, but still have the same problem.

### PR DESCRIPTION
**Pull request by Phype**
I've fixed the purei9_unoffical library by adding new authentication options.

I'll not implement the new API from https://developer.electrolux.one/ since this is already supported by https://github.com/JohNan/homeassistant-wellbeing/pull/145 now. However, the new API does not support all features yet, so its good to have a fallback.

This should fix #73.

### CODE REVIEW

**Comment by michaelfuncke** [comment]
So as this pull request has not been merged yet I installed Phype's clone repository via HACS. When trying to authenticate I get the "auth" error, though (email and pw correct).

What have I done wrong?

For me, the option to send the robot to certain zones is important. That's why JohNan's implementation is not suitable for me yet.

**Comment by joakimjalden** [comment]
> For me, the option to send the robot to certain zones is important. That's why JohNan's implementation is not suitable for me yet.

Just FYI, the (Electrolux developer) API that [JohNan/homeassistant-wellbeing](https://github.com/JohNan/homeassistant-wellbeing) uses does not at present support the commands needed to send the vacuum to specific zones. I've been in contact the developers at Electrolux to request that this feature be added. While their response was generally positive they were also upfront about it being a significant effort on their end and thus something that would need to be put against other priorities at the company. We will just have to wait and see if they can do it, after which adding the functionality to HA most likely would be straighforward.

They did however as part of our email conversation ask me to help support to a claim I made that this feature (i.e., zones) was highly requested by the HA community, to which I responded by sending them links to discussions I was aware of on forums and on GitHub, including the [Ekman/home-assistant-pure-i9](https://github.com/Ekman/home-assistant-pure-i9) and the [Phype/purei9_unofficial](https://github.com/Phype/purei9_unofficial) repos. While it is probably not helpful to overload them with emails, I do believe that constructively voicing our wishes for these features, including stable and uniform authentication across geographic regions for the APIs that purei9_unofficial use, in HA forums and also directly to Electrolux could help.

**Comment by Phype** [comment]
It was indeed caused by different region setings. I've updated purei9_unofficial and also the integration to pass an additional configuration parameter (the country code).

The integration needs to be re-initialized (integrations -> Pure i9 -> delete intergretation entry -> re add it) to set this value. The value should be the 2-character country code of your account, i.e. `SE` for sweden, `US`, etc, allthough different values will also work as long as they map to the same datacenter.

**Comment by michaelfuncke** [comment]
Great! That worked (country code `DE ` for Germany)! Thank you very much, @Phype!

**Comment by Ekman** [comment]
Thanks for the PR. I'll review it ASAP

**Pull request merged**
